name: Run linting on React App
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get the repository code
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
            - name: Run lint
              run: npm run lint
